server:
  port: 8888
  servlet:
    context-path: /app

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    #url: jdbc:h2:./test;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
    show-sql: true